export const bg = {
  "game.title": "Другарят Кандидат",
  "chapter1.title": "Изборен ден на село",
  "scene.chapter1.apartment.title": "Апартаментът на Бай Митко",
  "scene.chapter1.village_square.title": "Селският площад",
  "scene.chapter1.mehana.title": "Механа \"Двете кози\"",

  "ui.new_game": "Нова игра",
  "ui.continue": "Продължи",
  "ui.language": "Език",
  "ui.pause": "Пауза",
  "ui.resume": "Назад",
  "ui.save": "Запази",
  "ui.reset": "Изтрий",
  "ui.reset_confirm": "Да изтрия ли текущата игра, джобовете и всички записани предмети?",
  "ui.quests": "Задачи",
  "ui.hud": "Състояние на играта",
  "ui.inventory": "Инвентар",
  "ui.verb": "Действие",
  "ui.meter.influence": "Влияние",
  "ui.meter.suspicion": "Подозрение",
  "ui.meter.public_mood": "Народно настроение",
  "ui.hint": "Ляв бутон: действие. Десен бутон: сменя действие. Esc: пауза.",
  "npc.bai_mitko.name": "Бай Митко",

  "verb.look": "Виж",
  "verb.talk": "Говори",
  "verb.use": "Използвай",
  "verb.take": "Вземи",

  "exit.to_village_square": "Към площада",
  "exit.to_apartment": "Към апартамента",
  "exit.to_mehana": "Към механата",
  "exit.to_municipality": "Към общината",

  "item.accordion.name": "Акордеон",
  "item.accordion.desc": "Единственото нещо, което Бай Митко някога е свирил честно.",
  "item.unpaid_bills.name": "Неплатени сметки",
  "item.unpaid_bills.desc": "Финансова автобиография с печален край.",
  "msg.apartment.unpaid_bills_taken": "Сметките са прибрани. Доказателства не се оставят на масата, освен ако не са за гости.",
  "item.empty_envelope.name": "Празен плик",
  "item.empty_envelope.desc": "Празен, но с административен потенциал.",
  "item.fake_diploma.name": "Фалшива диплома",
  "item.fake_diploma.desc": "Изглежда достатъчно официално за хора, които не гледат внимателно.",
  "item.rakia.name": "Бутилка ракия",
  "item.rakia.desc": "Течна демокрация с висок градус.",
  "item.sunflower_oil.name": "Олио",
  "item.sunflower_oil.desc": "Народна медицина срещу тежки политически решения.",
  "item.glass_of_water.name": "Чаша вода",
  "item.glass_of_water.desc": "Безцветна, безпартийна и подозрително трезва.",
  "item.campaign_pamphlets.name": "Предизборни листовки",
  "item.campaign_pamphlets.desc": "Обещания на тънка хартия.",
  "item.suspicious_receipt.name": "Подозрителна касова бележка",
  "item.suspicious_receipt.desc": "Пише касова, звучи съдебна.",
  "item.pickle_jar.name": "Буркан с кисели краставички",
  "item.pickle_jar.desc": "Консерва с по-добра програма от повечето кандидати.",
  "item.ballot_box.name": "Избирателна урна",
  "item.ballot_box.desc": "Прозрачна по закон, мътна по традиция.",
  "item.municipality_stamp.name": "Общински печат",
  "item.municipality_stamp.desc": "Един малък печат отваря голяма врата.",

  "hotspot.wallpaper.name": "Лющен тапет",
  "hotspot.window.name": "Прозорец",
  "hotspot.campaign_poster.name": "Проектоплакат",
  "hotspot.mirror.name": "Напукано огледало",
  "hotspot.tv.name": "Стар телевизор",
  "hotspot.wardrobe.name": "Гардероб",
  "hotspot.table.name": "Евтина маса",
  "hotspot.poster_board.name": "Агитационно табло",
  "hotspot.fountain.name": "Фонтан",
  "hotspot.kiosk.name": "Вестникарска будка",
  "hotspot.statue.name": "Паметник",
  "hotspot.old_men_bench.name": "Пейка на старците",
  "hotspot.election_notice.name": "Изборно съобщение",
  "hotspot.water_jug.name": "Кана с вода",

  "npc.baba_stoyanka.name": "Баба Стоянка",
  "npc.tony_fridge.name": "Тони Хладилника",

  "look.apartment.wallpaper": "Тапетът се лющи с тихото достойнство на пенсиониран министър.",
  "look.apartment.window": "Прозорец към чист въздух, доколкото районът позволява.",
  "look.apartment.accordion": "Моят акордеон. Единственото нещо, което някога съм свирил честно.",
  "look.apartment.mirror": "Огледалото го показва на три части. Коалиционно излъчване.",
  "look.apartment.tv": "Телевизорът пак обяснява, че ситуацията е стабилна, но с извънреден характер.",
  "look.apartment.wardrobe": "Гардеробът пази дрехи от времена, когато Бай Митко още имаше план Б.",
  "look.apartment.table": "Маса за сметки, обещания и други хартиени трагедии.",
  "msg.apartment.window_opened": [
    "Мммм. Мирише ми на избори.",
    "Май някой пак е проветрил коалицията."
  ],
  "look.apartment.poster": "ГЛАСУВАЙ ЗА МИТКО: ПОНЕ ГО ПОЗНАВАШ. Силна програма, ако населението няма избор.",
  "look.square.poster_board": "Плакат върху плакат върху обещание. Археология на надеждата.",
  "look.square.fountain": "Фонтанът не работи, но поне не краде ток.",
  "look.square.kiosk": "Будката знае повече новини, отколкото продава.",
  "look.square.statue": "Паметник на местен герой от бюста нагоре. Отдолу бюджетът е свършил.",
  "look.square.old_men_bench": "Пейката е единствената социология с постоянна извадка.",
  "look.square.election_notice": "Пише, че изборите са прозрачни. Хартията обаче е леко мътна.",
  "look.mehana.oil": "Олио. В тази държава и салатата, и кариерата се плъзгат по него.",
  "look.mehana.water_jug": "Вода. Най-опасната течност в механата, защото буди съмнения.",
  "look.npc.baba_stoyanka": "Баба Стоянка гледа като човек, който е преживял три режима и четири ремонта на площада.",
  "look.npc.tony_fridge": "Тони Хладилника. Човек с гръб като секция и черен дроб като общински бюджет.",

  "msg.walk": "Бай Митко тръгва с походка на човек, който дължи пари в три посоки.",
  "msg.no_use": "Морално спорно, административно невъзможно.",
  "msg.taken": "Взето. Това изглежда полезно, или поне отричаемо.",
  "msg.already_taken": "Вече е прибрано. Бай Митко не повтаря кражба без причина.",
  "msg.need_talk": "Това не е разговор, това е инфраструктура.",
  "msg.scene_saved": "Запазено.",
  "msg.oil_used": "Бай Митко изпи олиото с изражение на човек, който инвестира в бъдещето.",
  "msg.accordion_tony": "Акордеонът разкъса тишината. Тони се сети за младостта и за една сервитьорка от 1998.",
  "msg.water_swap_success": "Тони уважаваше човек, който може да пие като хладилник. Бай Митко уважаваше водопровода.",
  "msg.water_swap_missing": "Без разсейване това ще изглежда като престъпление, а не като политика.",
  "msg.scene_not_ready": "Тази част от общината още е в ремонт на ремонта.",

  "quest.chapter1.main.title": "Стани кмет, преди кредиторите да те намерят.",
  "quest.chapter1.fake_diploma.title": "Направи диплома, достатъчно впечатляваща за избиратели, които не четат дипломи.",
  "quest.chapter1.baba_vote.title": "Убеди баба Стоянка, че твоята корупция поне е традиционна.",
  "quest.chapter1.tony_vote.title": "Спечели подкрепата на Тони Хладилника, без да изпаднеш в безсъзнание.",
  "quest.chapter1.journalist.title": "Оцелей пред въпросите на журналиста, без случайно да кажеш истината.",
  "quest.chapter1.ballot_box.title": "Намери изчезналата урна, преди някой да ферментира демокрацията.",

  "dialogue.common.back": "Назад.",
  "dialogue.tony.start": "Тони: Ако си дошъл за подкрепа, първо покажи капацитет. Тук капацитетът се мери в чаши.",
  "dialogue.tony.choice.challenge": "Да говорим за чашите.",
  "dialogue.tony.choice.politics": "Тони, селото има нужда от стабилност.",
  "dialogue.tony.choice.leave": "Ще стабилизирам отвън.",
  "dialogue.tony.politics": "Тони: Стабилност има в хладилника. Отваряш - вътре пак е студено.",
  "dialogue.tony.challenge": "Тони: Пием. Който мигне, гласува за стария кмет.",
  "dialogue.tony.choice.accept": "Приемам. Черният ми дроб е коалиционен.",
  "dialogue.tony.choice.refuse": "Още не. Трябва ми предизборна подготовка.",
  "dialogue.baba.start": "Баба Стоянка: Всички сте маскари, ама някои поне поздравяват.",
  "dialogue.baba.choice.tradition": "Моята корупция е традиционна.",
  "dialogue.baba.choice.promise": "Ще ремонтирам ремонта.",
  "dialogue.baba.choice.leave": "Ще мина пак, ако не ме намерят.",
  "dialogue.baba.tradition": "Баба Стоянка: Традиционна, викаш? Значи поне ще оставиш нещо за децата.",
  "dialogue.baba.promise": "Баба Стоянка: Ремонта го ремонтират откакто козата ми беше мома."
};
